// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ToDo_List
{
	public partial class ToDoTableViewController : UIViewController
	{
		public ToDoTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
