// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;

namespace ToDo_List
{
	public partial class ToDoTableViewController : UITableViewController
	{

		//private List<Movie> Movies { get; set; } = new List<Movie>();
		private List<ToDo> List { get; set; } = new List<ToDo>();

		public ToDoTableViewController(IntPtr handle) : base(handle)
		{
		}

		public override async void ViewDidLoad()
		{
			base.ViewDidLoad();
			List = await ToDoController.GetList();
			ToDoTableView.ReloadData();
		}

		public override nint RowsInSection(UITableView tableView, nint section)
		{
			return List.Count;
		}

		public override UITableViewCell GetCell(UITableView tableView, NSIndexPath indexPath)
		{
			var cell = TableView.DequeueReusableCell("ListCell", indexPath);
			var item = List[indexPath.Row];
			cell.TextLabel.Text = item.title;
			return cell;
		}

		//public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender)
		//{
		//	var vc = segue.DestinationViewController as MovieViewController;
		//	var indexPath = TableView.IndexPathForSelectedRow;
		//	var list = List[indexPath.Row];
		//	vc. = list;
		//}

		partial void addButtonTapped(NSObject sender)
		{
			UITextField textField = null;
			var alert = UIAlertController.Create("Add item", "", UIAlertControllerStyle.Alert);
			alert.AddTextField((field) =>
			{
				textField = field;
				textField.Placeholder = "Item name";
			});
			alert.AddAction(UIAlertAction.Create("Add", UIAlertActionStyle.Default, async (obj) =>
			{
				var item = new ToDo();
				item.title = textField.Text;
				var success = await ToDoController.AddItem(item);
				if (success)
				{
					List = await ToDoController.GetList();
					TableView.ReloadData();
				}
				else
				{
					NetworkError();
				}
			}));
			alert.AddAction(UIAlertAction.Create("Cancel", UIAlertActionStyle.Cancel, null));
			PresentViewController(alert, true, null);
		}

		void NetworkError()
		{
			var alert = UIAlertController.Create("Please check your network connection", "", UIAlertControllerStyle.Alert);
			alert.AddAction(UIAlertAction.Create("OK", UIAlertActionStyle.Cancel, null));
			PresentViewController(alert, true, null);
		}
	}

}
